create user "HRHR" identified by "1004";
grant connect, resource to "HRHR";
ALTER USER "HRHR" QUOTA UNLIMITED ON USERS;
commit;
--------------------------------------------------------
--  DDL 쿼리문 생성일자 - 화요일-9월-19-2023
--------------------------------------------------------

--------------------------------------------------------
--  DDL for Sequence EMPFAM_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "HRHR"."EMPFAM_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 121 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SWSMOTHER_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "HRHR"."SWSMOTHER_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 47 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Table CODE
--------------------------------------------------------

CREATE TABLE "HRHR"."CODE" 
(
    "PARENT_ID" VARCHAR2(100 BYTE), 
    "CODE_ID" VARCHAR2(100 BYTE), 
    "CODE_NAME" VARCHAR2(100 BYTE)
)  
TABLESPACE "USERS";

   COMMENT ON COLUMN "HRHR"."CODE"."PARENT_ID" IS '분류코드';
   COMMENT ON COLUMN "HRHR"."CODE"."CODE_ID" IS '코드아이디';
   COMMENT ON COLUMN "HRHR"."CODE"."CODE_NAME" IS '코드이름';
   COMMENT ON TABLE "HRHR"."CODE"  IS '코드테이블';
--------------------------------------------------------
--  DDL for Table DATE
--------------------------------------------------------

  CREATE TABLE "HRHR"."DATE" 
   (	"ALLOW_YEAR" VARCHAR2(100 BYTE), 
	"MONTH" VARCHAR2(100 BYTE) , 
	"DATE" VARCHAR2(100 BYTE), 
	"DATE_ID" VARCHAR2(100 BYTE)
   ) 
	TABLESPACE "USERS";
   COMMENT ON COLUMN "HRHR"."DATE"."ALLOW_YEAR" IS '귀속년';
   COMMENT ON COLUMN "HRHR"."DATE"."MONTH" IS '귀속연월';
   COMMENT ON COLUMN "HRHR"."DATE"."DATE" IS '날짜';
   COMMENT ON COLUMN "HRHR"."DATE"."DATE_ID" IS '날짜키';
--------------------------------------------------------
--  DDL for Table EMP
--------------------------------------------------------

  CREATE TABLE "HRHR"."EMP" 
   (	"CD_EMP" VARCHAR2(100 BYTE) PRIMARY KEY,
	"NM_KRNAME" VARCHAR2(100 BYTE) ,
	"YN_FOR" VARCHAR2(100 BYTE) ,
	"NO_SOCIAL" VARCHAR2(100 BYTE) ,
	"JOB_OK" VARCHAR2(100 BYTE)  DEFAULT 'Y', 
	"DA_ENTER" VARCHAR2(100 BYTE)  DEFAULT TO_CHAR(SYSDATE, 'YYYY-MM-DD'), 
	"FG_SEX" VARCHAR2(100 BYTE),
	"ABB_NATION" VARCHAR2(100 BYTE) ,
	"YN_RESIDENT" VARCHAR2(100 BYTE) ,
	"STR_39_1_1" VARCHAR2(100 BYTE),
	"STR_40_1_1" VARCHAR2(100 BYTE),
	"CD_NATION" VARCHAR2(100 BYTE),
	"ZIP_HOME" VARCHAR2(100 BYTE),
	"ADD_HOME1" VARCHAR2(300 BYTE),
	"ADD_HOME2" VARCHAR2(300 BYTE) ,
	"TEL_HOME1" VARCHAR2(100 BYTE),
	"TEL_HOME2" VARCHAR2(100 BYTE),
	"TEL_HOME3" VARCHAR2(100 BYTE),
	"CEL_EMP1" VARCHAR2(100 BYTE),
	"CEL_EMP2" VARCHAR2(100 BYTE) ,
	"CEL_EMP3" VARCHAR2(100 BYTE) ,
	"EM_EMP" VARCHAR2(300 BYTE) , 
	"ID_MSN" VARCHAR2(100 BYTE),
	"CD_DEPT" VARCHAR2(100 BYTE),
	"CD_OCCUP" VARCHAR2(100 BYTE),
	"RANK_NO" VARCHAR2(100 BYTE) ,
	"CD_SALCLS" VARCHAR2(100 BYTE),
	"CD_FIELD" VARCHAR2(100 BYTE) ,
	"CD_PROJECT" VARCHAR2(100 BYTE) ,
	"DA_RETIRE" VARCHAR2(100 BYTE),
	"CD_BANK" VARCHAR2(100 BYTE) ,
	"NO_BNKACCT" VARCHAR2(100 BYTE) ,
	"NM_BNKOWNER" VARCHAR2(100 BYTE),
	"MN_6_1_1" VARCHAR2(100 BYTE) ,
	"CD_ACCTIT1" VARCHAR2(100 BYTE),
	"CD_ACCTIT2" VARCHAR2(100 BYTE),
	"FG_PAYSUPPLY" VARCHAR2(100 BYTE) ,
	"MN_MMAVERAGE" VARCHAR2(100 BYTE) ,
	"MN_NATPTARGET" VARCHAR2(100 BYTE) ,
	"MN_NATPSLEV" VARCHAR2(100 BYTE),
	"MN_HOSTARGET" VARCHAR2(100 BYTE),
	"MN_HOS" VARCHAR2(100 BYTE) ,
	"NO_HEALTH" VARCHAR2(100 BYTE),
	"MN_EMPTARGET" VARCHAR2(100 BYTE) ,
	"MN_EMP" VARCHAR2(100 BYTE) ,
	"YN_EMPLOY" VARCHAR2(100 BYTE) ,
	"YN_CEO" VARCHAR2(100 BYTE) ,
	"YN_SANJAE" VARCHAR2(100 BYTE) ,
	"YN_LONGINSUR" VARCHAR2(100 BYTE),
	"STR_32_1_1" VARCHAR2(100 BYTE),
	"STR_33_1_1" VARCHAR2(100 BYTE) ,
	"STR_35_1_1" VARCHAR2(100 BYTE) ,
	"MN_2_1_1" VARCHAR2(100 BYTE) ,
	"MN_3_1_1" VARCHAR2(100 BYTE) ,
	"STR_1_1_1" VARCHAR2(100 BYTE) ,
	"STR_45_1_1" VARCHAR2(100 BYTE) ,
	"STR_46_1_1" VARCHAR2(100 BYTE),
	"STR_47_1_1" VARCHAR2(100 BYTE),
	"MN_1_1_1" VARCHAR2(100 BYTE),
	"YN_DANIL" VARCHAR2(100 BYTE) ,
	"YN_ICLMAN" VARCHAR2(100 BYTE),
	"STR_43_1_1" VARCHAR2(100 BYTE) ,
	"STR_44_1_1" VARCHAR2(100 BYTE),
	"MN_ICLPAY" VARCHAR2(100 BYTE),
	"STR_34_1_1" VARCHAR2(100 BYTE) ,
	"YN_FORLABOR" VARCHAR2(100 BYTE),
	"YN_UNIT" VARCHAR2(100 BYTE),
	"YN_OVERWORK" VARCHAR2(100 BYTE),
	"STR_42_1_1" VARCHAR2(100 BYTE),
	"MN_4_1_1" VARCHAR2(100 BYTE)
   ) 
  TABLESPACE "USERS" ;
 
--------------------------------------------------------
--  DDL for Table EMPADD
--------------------------------------------------------

  CREATE TABLE "HRHR"."EMPADD" 
(
    "CD_EMP" VARCHAR2(100 BYTE) PRIMARY KEY, 
    "NM_CHNAME" VARCHAR2(100 BYTE), 
    "NM_ENNAME" VARCHAR2(100 BYTE), 
    "NO_SOCIAL" VARCHAR2(100 BYTE), 
    "FG_SEX" VARCHAR2(100 BYTE), 
    "DA_BIRTH" VARCHAR2(100 BYTE), 
    "FG_WEDDING" VARCHAR2(100 BYTE), 
    "CD_DEPT" VARCHAR2(100 BYTE), 
    "RANK_NO" VARCHAR2(100 BYTE), 
    "CD_OFFDUTY" VARCHAR2(100 BYTE), 
    "YN_DRAWCONTRACTS" VARCHAR2(100 BYTE), 
    "DA_ENTER" VARCHAR2(100 BYTE), 
    "DA_RETIRE" VARCHAR2(100 BYTE), 
    "TY_EMPLOY" VARCHAR2(100 BYTE), 
    "DC_MIDRETIRE" VARCHAR2(100 BYTE), 
    "FG_DISORDER" VARCHAR2(100 BYTE), 
    "STR_HOBBY" VARCHAR2(100 BYTE), 
    "NM_SPECIAL" VARCHAR2(100 BYTE),
    "TY_RELIGION" VARCHAR2(100 BYTE), 
    "ZIP_HOME" VARCHAR2(100 BYTE), 
    "ADD_HOME1" VARCHAR2(100 BYTE),
    "ADD_HOME2" VARCHAR2(100 BYTE),
    "ZIP_ORGIN" VARCHAR2(100 BYTE), 
    "ADD_ORGIN1" VARCHAR2(300 BYTE), 
    "ADD_ORGIN2" VARCHAR2(100 BYTE), 
    "MN_KEEPGARDEN" VARCHAR2(100 BYTE), 
    "MN_KEEPESTATE" VARCHAR2(100 BYTE), 
    "FG_OWNHOUSE" VARCHAR2(100 BYTE), 
    "TEL_HOME1" VARCHAR2(100 BYTE), 
    "TEL_HOME2" VARCHAR2(100 BYTE), 
    "TEL_HOME3" VARCHAR2(100 BYTE),
    "CEL_EMP1" VARCHAR2(100 BYTE), 
    "CEL_EMP2" VARCHAR2(100 BYTE), 
    "CEL_EMP3" VARCHAR2(100 BYTE), 
    "TEL_OFFICE1" VARCHAR2(100 BYTE), 
    "TEL_OFFICE2" VARCHAR2(100 BYTE), 
    "TEL_OFFICE3" VARCHAR2(100 BYTE), 
    "DA_MLTBEGIN" VARCHAR2(100 BYTE), 
    "TEL_EXTENS" VARCHAR2(100 BYTE), 
    "TY_MILIT" VARCHAR2(100 BYTE), 
    "WHY_MLTOFF" VARCHAR2(100 BYTE), 
    "DA_MLTEND" VARCHAR2(100 BYTE), 
    "FG_MLTTYPE" VARCHAR2(100 BYTE), 
    "NM_MLTBRANC" VARCHAR2(100 BYTE), 
    "STR_MLTDISCH" VARCHAR2(100 BYTE), 
    "CD_MLTRANK" VARCHAR2(100 BYTE)
)  
TABLESPACE "USERS";


-- 외래 키(FK) 설정 및 CASCADE 옵션 추가
ALTER TABLE "HRHR"."EMPADD"
ADD CONSTRAINT "FK_EMPADD_EMP" 
FOREIGN KEY ("CD_EMP") 
REFERENCES "HRHR"."EMP" ("CD_EMP")
ON DELETE CASCADE;

--EMP테이블과 중복되는 EMPADD 컬럼의 ON UPDATE CASCADE를 구현하는 트리거
CREATE OR REPLACE TRIGGER "HRHR"."EMP_UPDATE_TRIGGER"
AFTER UPDATE OF NO_SOCIAL, FG_SEX, CD_DEPT, RANK_NO, DA_ENTER, DA_RETIRE ON "HRHR".EMP
FOR EACH ROW
BEGIN
    UPDATE "HRHR".EMPADD
    SET 
        NO_SOCIAL = :NEW.NO_SOCIAL,
        FG_SEX = :NEW.FG_SEX,
        CD_DEPT = :NEW.CD_DEPT,
        RANK_NO = :NEW.RANK_NO,
        DA_ENTER = :NEW.DA_ENTER,
        DA_RETIRE = :NEW.DA_RETIRE
    WHERE
        CD_EMP = :NEW.CD_EMP;
END;

   COMMENT ON COLUMN "HRHR"."EMPADD"."CD_EMP" IS '사원코드';
   COMMENT ON COLUMN "HRHR"."EMPADD"."NM_CHNAME" IS '한자성명';
   COMMENT ON COLUMN "HRHR"."EMPADD"."NM_ENNAME" IS '영문성명';
   COMMENT ON COLUMN "HRHR"."EMPADD"."YN_DRAWCONTRACTS" IS '근로계약서';
   COMMENT ON COLUMN "HRHR"."EMPADD"."FG_WEDDING" IS '결혼여부';
   COMMENT ON COLUMN "HRHR"."EMPADD"."DA_BIRTH" IS '생년월일';
   COMMENT ON COLUMN "HRHR"."EMPADD"."STR_HOBBY" IS '취미';
   COMMENT ON COLUMN "HRHR"."EMPADD"."NM_SPECIAL" IS '특기';
   COMMENT ON COLUMN "HRHR"."EMPADD"."NO_SOCIAL" IS '주민등록번호';
   COMMENT ON COLUMN "HRHR"."EMPADD"."FG_SEX" IS '성별';
   COMMENT ON COLUMN "HRHR"."EMPADD"."CD_DEPT" IS '부서';
   COMMENT ON COLUMN "HRHR"."EMPADD"."RANK_NO" IS '직급';
   COMMENT ON COLUMN "HRHR"."EMPADD"."DA_ENTER" IS '입사년월일';
   COMMENT ON COLUMN "HRHR"."EMPADD"."DA_RETIRE" IS '퇴사년월일';
   COMMENT ON COLUMN "HRHR"."EMPADD"."CD_OFFDUTY" IS '직무';
--------------------------------------------------------
--  DDL for Table EMPFAM
--------------------------------------------------------

CREATE TABLE "HRHR"."EMPFAM" 
(
    "SEQ_VAL" NUMBER DEFAULT "HRHR"."EMPFAM_SEQ"."NEXTVAL", 
    "CD_EMP" VARCHAR2(100 BYTE), 
    "CD_CALREL" VARCHAR2(100 BYTE), 
    "CD_FAMREL" VARCHAR2(100 BYTE), 
    "NM_KRNAME" VARCHAR2(100 BYTE), 
    "YN_FOR" VARCHAR2(100 BYTE), 
    "NO_SOCIAL" VARCHAR2(100 BYTE), 
    "FG_SCHOOL" VARCHAR2(100 BYTE), 
    "FG_GRADUATION" VARCHAR2(100 BYTE), 
    "YN_TOGETHER" VARCHAR2(100 BYTE), 
    "YN_LUNARBIR" VARCHAR2(100 BYTE), 
    "DA_BIRTH" VARCHAR2(100 BYTE), 
    "CD_JOB" VARCHAR2(100 BYTE), 
    "NM_KRCOM" VARCHAR2(300 BYTE), 
    "CD_OFFPOS" VARCHAR2(100 BYTE)
) 
TABLESPACE "USERS";

ALTER TABLE "HRHR"."EMPFAM"
ADD CONSTRAINT "PK_EMPFAM" PRIMARY KEY ("CD_EMP", "SEQ_VAL");

ALTER TABLE "HRHR"."EMPFAM"
ADD CONSTRAINT "FK_EMPFAM_EMPADD" FOREIGN KEY ("CD_EMP") 
REFERENCES "HRHR"."EMPADD" ("CD_EMP")
ON DELETE CASCADE;

--------------------------------------------------------
--  DDL for Table EMPLOYEE
--------------------------------------------------------

CREATE TABLE "HRHR"."EMPLOYEE" 
(
    "EMPLOYEEID" NUMBER PRIMARY KEY, 
    "EMPLOYEENAME" VARCHAR2(255 BYTE), 
    "MANAGERID" NUMBER
)
TABLESPACE "USERS";
--------------------------------------------------------
--  DDL for Table EMPMENUUSAGE
--------------------------------------------------------

CREATE TABLE "HRHR"."EMPMENUUSAGE" 
(
    "CD_EMP" VARCHAR2(100 BYTE) PRIMARY KEY, 
    "USE_MENULIST" CLOB
)
TABLESPACE "USERS"
LOB ("USE_MENULIST") STORE AS SECUREFILE 
(
    TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192
);
--------------------------------------------------------
--  DDL for Table EMPPHOTO
--------------------------------------------------------
CREATE TABLE "HRHR"."EMPPHOTO" 
(
    "CD_EMP" VARCHAR2(100 BYTE), 
    "NM_PHOTO" VARCHAR2(100 BYTE), 
    "FILE_PATH" VARCHAR2(100 BYTE), 
    "UUID" VARCHAR2(100 BYTE)
)
TABLESPACE "USERS";

ALTER TABLE "HRHR"."EMPPHOTO"
ADD CONSTRAINT "PK_EMPPHOTO" PRIMARY KEY ("CD_EMP");

ALTER TABLE "HRHR"."EMPPHOTO"
ADD CONSTRAINT "FK_EMPPHOTO_EMPADD" 
FOREIGN KEY ("CD_EMP") 
REFERENCES "HRHR"."EMPADD" ("CD_EMP")
    ON DELETE CASCADE;
--------------------------------------------------------
--  DDL for Table EMP_PAYROLL_CRITERIA
--------------------------------------------------------

CREATE TABLE "HRHR"."EMP_PAYROLL_CRITERIA" 
(
    "CD_EMP" VARCHAR2(100 BYTE), 
    "ALLOW_MONTH" VARCHAR2(100 BYTE), 
    "WORKDAY" VARCHAR2(100 BYTE), 
    "OVERTIME" VARCHAR2(100 BYTE), 
    "HOURLYWAGE" VARCHAR2(100 BYTE)
)
TABLESPACE "USERS";

   COMMENT ON COLUMN "HRHR"."EMP_PAYROLL_CRITERIA"."CD_EMP" IS '사원번호';
   COMMENT ON COLUMN "HRHR"."EMP_PAYROLL_CRITERIA"."ALLOW_MONTH" IS '귀속년월';
   COMMENT ON COLUMN "HRHR"."EMP_PAYROLL_CRITERIA"."WORKDAY" IS '근무일수';
   COMMENT ON COLUMN "HRHR"."EMP_PAYROLL_CRITERIA"."OVERTIME" IS '초과근무시간';
   COMMENT ON COLUMN "HRHR"."EMP_PAYROLL_CRITERIA"."HOURLYWAGE" IS '통상시급(임금계산기초사항)';
   COMMENT ON TABLE "HRHR"."EMP_PAYROLL_CRITERIA"  IS '사원별 임금계산기준 항목(근무일수, 초과근무 시간)';
--------------------------------------------------------
--  DDL for Table MEMBER
--------------------------------------------------------

CREATE TABLE "HRHR"."MEMBER" 
(
    "COMPANY_CODE" VARCHAR2(100 BYTE), 
    "USER_ID" VARCHAR2(100 BYTE), 
    "USER_PWD" VARCHAR2(100 BYTE), 
    "EMP_IMG" VARCHAR2(100 BYTE)
)
TABLESPACE "USERS";
--------------------------------------------------------
--  DDL for Table SAALLOW
--------------------------------------------------------

CREATE TABLE "HRHR"."SAALLOW" 
(
    "CD_ALLOW" VARCHAR2(100 BYTE), 
    "YN_TAX" VARCHAR2(100 BYTE), 
    "NM_ALLOW" VARCHAR2(100 BYTE), 
    "SAL_DIVISION" VARCHAR2(100 BYTE), 
    "MONTHLY_YN" VARCHAR2(100 BYTE), 
    "COMMONLY_YN" VARCHAR2(100 BYTE), 
    "NONTAX_LIMIT" VARCHAR2(100 BYTE), 
    "NONTAX_DIVISON" VARCHAR2(100 BYTE), 
    "ORDER" NUMBER(*,0)
)
TABLESPACE "USERS";

   COMMENT ON COLUMN "HRHR"."SAALLOW"."CD_ALLOW" IS '급여항목코드';
   COMMENT ON COLUMN "HRHR"."SAALLOW"."YN_TAX" IS '과세/비과세';
   COMMENT ON COLUMN "HRHR"."SAALLOW"."NM_ALLOW" IS '급여항목이름';
   COMMENT ON COLUMN "HRHR"."SAALLOW"."SAL_DIVISION" IS '구분(급여, 상여)';
   COMMENT ON COLUMN "HRHR"."SAALLOW"."MONTHLY_YN" IS '월정액 급여 포함여부';
   COMMENT ON COLUMN "HRHR"."SAALLOW"."COMMONLY_YN" IS '통상임금 포함여부';
   COMMENT ON COLUMN "HRHR"."SAALLOW"."NONTAX_LIMIT" IS '비과세항목 한도';
   COMMENT ON COLUMN "HRHR"."SAALLOW"."NONTAX_DIVISON" IS '비과세항목 구분';
   COMMENT ON COLUMN "HRHR"."SAALLOW"."ORDER" IS '순서';
   COMMENT ON TABLE "HRHR"."SAALLOW"  IS '급여항목';
--------------------------------------------------------
--  DDL for Table SAALLOWPAY
--------------------------------------------------------

CREATE TABLE "HRHR"."SAALLOWPAY" 
(
    "CD_ALLOW" VARCHAR2(100 BYTE), 
    "ALLOW_PAY" VARCHAR2(100 BYTE), 
    "CD_EMP" VARCHAR2(100 BYTE), 
    "DATE_ID" VARCHAR2(100 BYTE), 
    "YN_TAX" VARCHAR2(100 BYTE)
) 
TABLESPACE "USERS";


   COMMENT ON COLUMN "HRHR"."SAALLOWPAY"."CD_ALLOW" IS '급여항목코드';
   COMMENT ON COLUMN "HRHR"."SAALLOWPAY"."ALLOW_PAY" IS '급여항목 지급 금액';
   COMMENT ON COLUMN "HRHR"."SAALLOWPAY"."CD_EMP" IS '사원번호';
   COMMENT ON COLUMN "HRHR"."SAALLOWPAY"."DATE_ID" IS 'date key';
   COMMENT ON COLUMN "HRHR"."SAALLOWPAY"."YN_TAX" IS '과세여부';
   COMMENT ON TABLE "HRHR"."SAALLOWPAY"  IS '급여_급여항목';
--------------------------------------------------------
--  DDL for Table SAALLOW_CALCULATION
--------------------------------------------------------

CREATE TABLE "HRHR"."SAALLOW_CALCULATION" 
(
    "CD_ALLOW" VARCHAR2(100 BYTE), 
    "CD_EMP" VARCHAR2(100 BYTE), 
    "RATE" VARCHAR2(100 BYTE), 
    "CONSTANT" VARCHAR2(100 BYTE)
) 
TABLESPACE "USERS";


   COMMENT ON COLUMN "HRHR"."SAALLOW_CALCULATION"."CD_ALLOW" IS '급여항목';
   COMMENT ON COLUMN "HRHR"."SAALLOW_CALCULATION"."CD_EMP" IS '사원ID';
   COMMENT ON COLUMN "HRHR"."SAALLOW_CALCULATION"."RATE" IS '비율(연장근로시간*1.5)';
   COMMENT ON COLUMN "HRHR"."SAALLOW_CALCULATION"."CONSTANT" IS '상수(팀장대행 2만원)';
   COMMENT ON TABLE "HRHR"."SAALLOW_CALCULATION"  IS '사원별 지급항목 계산식';
--------------------------------------------------------
--  DDL for Table SADEDUCT
--------------------------------------------------------

CREATE TABLE "HRHR"."SADEDUCT" 
(
    "CD_DEDUCT" VARCHAR2(100 BYTE), 
    "NM_DEDUCT" VARCHAR2(100 BYTE), 
    "YN_BONUS" VARCHAR2(100 BYTE), 
    "YN_SAL" VARCHAR2(100 BYTE)
) 
TABLESPACE "USERS";

   COMMENT ON COLUMN "HRHR"."SADEDUCT"."CD_DEDUCT" IS '공제항목 코드';
   COMMENT ON COLUMN "HRHR"."SADEDUCT"."NM_DEDUCT" IS '공제항목 이름';
   COMMENT ON COLUMN "HRHR"."SADEDUCT"."YN_BONUS" IS '상여여부';
   COMMENT ON COLUMN "HRHR"."SADEDUCT"."YN_SAL" IS '급여여부';
   COMMENT ON TABLE "HRHR"."SADEDUCT"  IS '공제항목';
--------------------------------------------------------
--  DDL for Table SADEDUCTPAY
--------------------------------------------------------

CREATE TABLE "HRHR"."SADEDUCTPAY" 
(
    "CD_DEDUCT" VARCHAR2(100 BYTE), 
    "ALLOW_PAY" VARCHAR2(100 BYTE), 
    "CD_EMP" VARCHAR2(100 BYTE), 
    "DATE_ID" VARCHAR2(100 BYTE)
) 
TABLESPACE "USERS";


   COMMENT ON COLUMN "HRHR"."SADEDUCTPAY"."CD_DEDUCT" IS '공제항목,급여항목 코드';
   COMMENT ON COLUMN "HRHR"."SADEDUCTPAY"."ALLOW_PAY" IS '지급 금액';
   COMMENT ON COLUMN "HRHR"."SADEDUCTPAY"."CD_EMP" IS '사원번호';
   COMMENT ON COLUMN "HRHR"."SADEDUCTPAY"."DATE_ID" IS 'dateid';
   COMMENT ON TABLE "HRHR"."SADEDUCTPAY"  IS '사원별 지급액';
--------------------------------------------------------
--  DDL for Table SADEDUCT_CALCULATION
--------------------------------------------------------

CREATE TABLE "HRHR"."SADEDUCT_CALCULATION" 
(
    "CD_DEDUCT" VARCHAR2(100 BYTE), 
    "CD_EMP" VARCHAR2(100 BYTE), 
    "RATE" VARCHAR2(100 BYTE), 
    "PROGRESSIVE_TAX" VARCHAR2(100 BYTE)
) 
TABLESPACE "USERS";


   COMMENT ON COLUMN "HRHR"."SADEDUCT_CALCULATION"."CD_DEDUCT" IS '공제항목';
   COMMENT ON COLUMN "HRHR"."SADEDUCT_CALCULATION"."CD_EMP" IS '사원ID';
   COMMENT ON COLUMN "HRHR"."SADEDUCT_CALCULATION"."RATE" IS '비율';
   COMMENT ON COLUMN "HRHR"."SADEDUCT_CALCULATION"."PROGRESSIVE_TAX" IS '누진세';
   COMMENT ON TABLE "HRHR"."SADEDUCT_CALCULATION"  IS '사원별 공제항목 계산식';
--------------------------------------------------------
--  DDL for Table SAEMPINFO
--------------------------------------------------------

  CREATE TABLE "HRHR"."SAEMPINFO" 
(
    "CD_EMP" VARCHAR2(100 BYTE), 
    "MN_1_1_1" VARCHAR2(100 BYTE), 
    "DA_ENTER" VARCHAR2(100 BYTE), 
    "YN_MATEDED" VARCHAR2(100 BYTE), 
    "NUM_20FAMILY" VARCHAR2(100 BYTE), 
    "NUM_60FAMILY" VARCHAR2(100 BYTE), 
    "NUM_MANYFAMILY" VARCHAR2(100 BYTE), 
    "YN_RESIDENT" VARCHAR2(100 BYTE), 
    "YN_UNIT" VARCHAR2(100 BYTE), 
    "YN_FORLABOR" VARCHAR2(100 BYTE), 
    "YN_OVERWORK" VARCHAR2(100 BYTE), 
    "DA_RETIRE" VARCHAR2(100 BYTE), 
    "CD_OCCUP" VARCHAR2(100 BYTE), 
    "RANK_NO" VARCHAR2(100 BYTE), 
    "CD_DEPT" VARCHAR2(100 BYTE), 
    "CD_FIELD" VARCHAR2(100 BYTE), 
    "CD_PROJECT" VARCHAR2(100 BYTE), 
    "AM_NATIONPEN" VARCHAR2(100 BYTE), 
    "AM_HEALTHINSUR" VARCHAR2(100 BYTE), 
    "MN_2_1_1" VARCHAR2(100 BYTE), 
    "NO_SOCIAL" VARCHAR2(100 BYTE), 
    "MN_REDUCTION" VARCHAR2(100 BYTE), 
    "HOURLYWAGE" VARCHAR2(100 BYTE)
) 
TABLESPACE "USERS";

   COMMENT ON COLUMN "HRHR"."SAEMPINFO"."CD_EMP" IS '사원코드';
   COMMENT ON COLUMN "HRHR"."SAEMPINFO"."MN_1_1_1" IS '중소기업 취업감면_감면율';
   COMMENT ON COLUMN "HRHR"."SAEMPINFO"."DA_ENTER" IS '입사일자';
   COMMENT ON COLUMN "HRHR"."SAEMPINFO"."YN_MATEDED" IS '배우자공제';
   COMMENT ON COLUMN "HRHR"."SAEMPINFO"."NUM_20FAMILY" IS '20세';
   COMMENT ON COLUMN "HRHR"."SAEMPINFO"."NUM_60FAMILY" IS '60세';
   COMMENT ON COLUMN "HRHR"."SAEMPINFO"."NUM_MANYFAMILY" IS '다자녀';
   COMMENT ON COLUMN "HRHR"."SAEMPINFO"."YN_RESIDENT" IS '거주구분';
   COMMENT ON COLUMN "HRHR"."SAEMPINFO"."YN_UNIT" IS '생산직여부';
   COMMENT ON COLUMN "HRHR"."SAEMPINFO"."YN_FORLABOR" IS '국외근로여부';
   COMMENT ON COLUMN "HRHR"."SAEMPINFO"."YN_OVERWORK" IS '연장근로비과세';
   COMMENT ON COLUMN "HRHR"."SAEMPINFO"."DA_RETIRE" IS '퇴사일자';
   COMMENT ON COLUMN "HRHR"."SAEMPINFO"."CD_OCCUP" IS '직종';
   COMMENT ON COLUMN "HRHR"."SAEMPINFO"."RANK_NO" IS '직급';
   COMMENT ON COLUMN "HRHR"."SAEMPINFO"."CD_DEPT" IS '부서';
   COMMENT ON COLUMN "HRHR"."SAEMPINFO"."CD_FIELD" IS '현장';
   COMMENT ON COLUMN "HRHR"."SAEMPINFO"."CD_PROJECT" IS '프로젝트';
   COMMENT ON COLUMN "HRHR"."SAEMPINFO"."AM_NATIONPEN" IS '국민연금보험료';
   COMMENT ON COLUMN "HRHR"."SAEMPINFO"."AM_HEALTHINSUR" IS '건강보험료';
   COMMENT ON COLUMN "HRHR"."SAEMPINFO"."MN_2_1_1" IS '두루누리 적용율_고용';
   COMMENT ON COLUMN "HRHR"."SAEMPINFO"."NO_SOCIAL" IS '주민번호';
   COMMENT ON COLUMN "HRHR"."SAEMPINFO"."MN_REDUCTION" IS '감면율(임시 칼럼)';
   COMMENT ON COLUMN "HRHR"."SAEMPINFO"."HOURLYWAGE" IS '통상시급';
   COMMENT ON TABLE "HRHR"."SAEMPINFO"  IS '급여_사원';
--------------------------------------------------------
--  DDL for Table SWSM
--------------------------------------------------------

 CREATE TABLE "HRHR"."SWSM" 
(
    "INCOME_CLASSFICATION" VARCHAR2(100 BYTE), 
    "WITHHOLDING_YEAR" VARCHAR2(100 BYTE), 
    "DATE_OF_CREATION" VARCHAR2(100 BYTE), 
    "CD_EMP" VARCHAR2(100 BYTE), 
    "OTHER_BENEFITS_ITEM" VARCHAR2(100 BYTE), 
    "OTHER_BENEFITS_AMOUNT" VARCHAR2(100 BYTE), 
    "NM_KRNAME" VARCHAR2(100 BYTE), 
    "RESIDENT_STATE" VARCHAR2(100 BYTE), 
    "RRN" VARCHAR2(100 BYTE), 
    "SALARY_AMOUNT" VARCHAR2(100 BYTE), 
    "BONUS_AMOUNT" VARCHAR2(100 BYTE), 
    "START_EMP_CONTRACT_PERIOD" VARCHAR2(100 BYTE), 
    "END_EMP_CONTRACT_PERIOD" VARCHAR2(100 BYTE), 
    "POST_CODE" VARCHAR2(100 BYTE), 
    "ADDRESS" VARCHAR2(100 BYTE), 
    "JOB_DESCRIPTION" VARCHAR2(100 BYTE), 
    "START_BREAK_TIME" VARCHAR2(100 BYTE), 
    "END_BREAK_TIME" VARCHAR2(100 BYTE), 
    "WORKING_DAY" VARCHAR2(100 BYTE), 
    "DAY_OFF" VARCHAR2(100 BYTE), 
    "SALARY_TYPE" VARCHAR2(100 BYTE), 
    "OTHER_BENEFITS" VARCHAR2(100 BYTE), 
    "BONUS_PAYMENT_STATUS" VARCHAR2(100 BYTE), 
    "SALARY_PAYMENT_DATE_TYPE" VARCHAR2(100 BYTE), 
    "PAYMENT_DATE" VARCHAR2(100 BYTE), 
    "PAYMENT_METHOD" VARCHAR2(100 BYTE), 
    "EMP_INSURANCE" VARCHAR2(100 BYTE), 
    "COMPENSATION_INSURANCE" VARCHAR2(100 BYTE), 
    "NATIONAL_PENSION" VARCHAR2(100 BYTE), 
    "HEALTH_INSURANCE" VARCHAR2(100 BYTE), 
    "ADD_DETAIL" VARCHAR2(100 BYTE), 
    "START_WORKTIME" VARCHAR2(100 BYTE), 
    "END_WORKTIME" VARCHAR2(100 BYTE)
) 
TABLESPACE "USERS";

--------------------------------------------------------
--  DDL for Table SWSMOTHER
--------------------------------------------------------

CREATE TABLE "HRHR"."SWSMOTHER" 
(
    "OTHER_TYPE" VARCHAR2(100 BYTE), 
    "OTHER_MONEY" VARCHAR2(100 BYTE), 
    "CD_EMP" VARCHAR2(100 BYTE), 
    "SEQ_VAL" VARCHAR2(100 BYTE) DEFAULT "HRHR"."SWSMOTHER_SEQ"."NEXTVAL"
) 
TABLESPACE "USERS";

--------------------------------------------------------
--  DDL for Table USER
--------------------------------------------------------

CREATE TABLE "HRHR"."USER" 
(
    "COMPANY_CODE" VARCHAR2(100 BYTE), 
    "USER_ID" VARCHAR2(100 BYTE), 
    "USER_PWD" VARCHAR2(100 BYTE)
) 
TABLESPACE "USERS";

