name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew

    - name: Build with Gradle
      run: ./gradlew build

    - name: Copy files to AWS EC2
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.AWS_SERVER_HOST }}
        username: ${{ secrets.AWS_SERVER_USER }}
        key: ${{ secrets.AWS_SERVER_SSH_KEY }}
        source: "./build/libs/*"
        target: "/home/ubuntu/temp"

    - name: Restart application on AWS EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.AWS_SERVER_HOST }}
        username: ${{ secrets.AWS_SERVER_USER }}
        key: ${{ secrets.AWS_SERVER_SSH_KEY }}
        script: |
          pkill java
          nohup java -jar /home/ubuntu/temp/build/libs/infinite-douzone-backend-0.0.1-SNAPSHOT.jar &
          sleep 10
